const fs = require('fs');
const path = require('path');

const projectRoot = path.join(__dirname, '..');
const htmlPath = path.join(projectRoot, 'block.html');
const destPath = path.join(projectRoot, 'src', 'index.js');

// Create src/ directory if it doesn't exist
const srcDir = path.join(projectRoot, 'src');
if (!fs.existsSync(srcDir)) {
    fs.mkdirSync(srcDir, { recursive: true });
}

console.log('Reading block.html...');
// Read HTML content
let htmlContent = fs.readFileSync(htmlPath, 'utf8');

console.log('Escaping HTML content for embedding...');
// Escape backticks and placeholders in HTML so it can be safely embedded in a template literal
const escapedHtml = htmlContent
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\${/g, '\\${');

// Generate index.js content
const jsContent = `// Cloudflare Workers Entry Point - Auto-generated from block.html
// DO NOT EDIT THIS FILE DIRECTLY. Edit block.html or scripts/build.js.

// Temporary in-memory fallback cache if LEADERBOARD_KV is not bound or fails
const memoryCache = {
  leaderboard_5: [],
  leaderboard_9: [],
  leaderboard_12: [],
  leaderboard_5_timed: [],
  leaderboard_9_timed: [],
  leaderboard_12_timed: []
};

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const path = url.pathname;

    // Route: GET / (Serve the main HTML page)
    if (path === '/' || path === '/index.html') {
      const html = \`${escapedHtml}\`;
      return new Response(html, {
        headers: {
          'Content-Type': 'text/html;charset=UTF-8',
          'Cache-Control': 'no-cache, no-store, must-revalidate',
        },
      });
    }

    // Route: GET /api/leaderboard?size=5|9|12&mode=infinite|timed
    if (path === '/api/leaderboard' && request.method === 'GET') {
      const size = url.searchParams.get('size') || '9';
      const mode = url.searchParams.get('mode') || 'infinite';
      if (!['5', '9', '12'].includes(size) || !['infinite', 'timed'].includes(mode)) {
        return new Response(JSON.stringify({ error: 'Invalid size or mode' }), {
          status: 400,
          headers: { 'Content-Type': 'application/json' },
        });
      }

      let scores = [];
      const scoreKey = mode === 'infinite' ? \`leaderboard_\${size}\` : \`leaderboard_\${size}_timed\`;
      try {
        if (env.LEADERBOARD_KV) {
          const val = await env.LEADERBOARD_KV.get(scoreKey);
          if (val) {
            scores = JSON.parse(val);
          }
        } else {
          scores = memoryCache[scoreKey] || [];
        }
      } catch (e) {
        console.error("KV Read Error, falling back to memory:", e);
        scores = memoryCache[scoreKey] || [];
      }

      return new Response(JSON.stringify(scores), {
        headers: { 
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*'
        },
      });
    }

    // Route: POST /api/leaderboard
    if (path === '/api/leaderboard' && request.method === 'POST') {
      try {
        const body = await request.json();
        const { size, name, score, mode } = body;
        const modeStr = (mode || 'infinite').toString();
        
        if (!size || !name || typeof score !== 'number' || 
            !['5', '9', '12'].includes(size.toString()) || 
            !['infinite', 'timed'].includes(modeStr)) {
          return new Response(JSON.stringify({ error: 'Invalid input parameters' }), {
            status: 400,
            headers: { 'Content-Type': 'application/json' },
          });
        }

        const sizeStr = size.toString();
        const scoreKey = modeStr === 'infinite' ? \`leaderboard_\${sizeStr}\` : \`leaderboard_\${sizeStr}_timed\`;

        // 1. Get existing scores
        let scores = [];
        let usingKV = false;
        try {
          if (env.LEADERBOARD_KV) {
            const val = await env.LEADERBOARD_KV.get(scoreKey);
            if (val) {
              scores = JSON.parse(val);
            }
            usingKV = true;
          } else {
            scores = memoryCache[scoreKey] || [];
          }
        } catch (e) {
          console.error("KV Read during write error:", e);
          scores = memoryCache[scoreKey] || [];
        }

        // 2. Add new score
        scores.push({
          name: name.slice(0, 20) || "無名大師",
          score: parseInt(score, 10),
          date: new Date().toLocaleDateString('zh-TW', { timeZone: 'Asia/Taipei' })
        });

        // 3. Sort and slice top 10
        scores.sort((a, b) => b.score - a.score);
        scores = scores.slice(0, 10);

        // 4. Save back
        try {
          if (usingKV && env.LEADERBOARD_KV) {
            await env.LEADERBOARD_KV.put(scoreKey, JSON.stringify(scores));
          } else {
            memoryCache[scoreKey] = scores;
          }
        } catch (e) {
          console.error("KV Write Error, saving to memory instead:", e);
          memoryCache[scoreKey] = scores;
        }

        return new Response(JSON.stringify(scores), {
          headers: { 
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*'
          },
        });
      } catch (e) {
        return new Response(JSON.stringify({ error: 'Invalid request body or server error', details: e.message }), {
          status: 500,
          headers: { 'Content-Type': 'application/json' },
        });
      }
    }

    // CORS preflight requests
    if (request.method === 'OPTIONS') {
      return new Response(null, {
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type',
        },
      });
    }

    // Default: 404 Not Found
    return new Response('Not Found', { status: 404 });
  },
};
`;

console.log('Writing bundled output to src/index.js...');
fs.writeFileSync(destPath, jsContent, 'utf8');
console.log('Successfully bundled block.html into src/index.js!');
